#!/usr/bin/env node
/* eslint-env node */
/* eslint no-console: "off" */
const chalk = require('chalk');
const { initORM } = require('@datawrapper/orm');
const config = require('../src/config');

initORM(config).then(({ db }) => {
    // add missing tables without touching existing ones
    db.sync().then(() => {
        console.log(chalk.green('database sync complete.\n'));
        db.close();
    }).catch(error => {
        console.error(error);
        db.close();
    });
});
