export default {
    visualize: {
        'text-annotations': [
            {
                x: 50,
                y: 180,
                bg: false,
                dx: 0,
                dy: 0,
                bold: false,
                size: 14,
                text: 'Share of working-age Americans experiencing\n50 percent or greater drops in family income\nover two-year periods.',
                align: 'mr',
                color: '#222',
                width: 40,
                italic: false,
                underline: false,
                showMobile: true,
                showDesktop: true,
                mobileFallback: true,
                connectorLine: {
                    type: 'straight',
                    circle: false,
                    stroke: 1,
                    enabled: false,
                    arrowHead: 'lines',
                    circleStyle: 'solid',
                    circleRadius: 15,
                    targetPadding: 4,
                    inheritColor: false
                }
            },
            {
                x: 450,
                y: 80,
                bg: false,
                dx: 0,
                dy: 0,
                bold: true,
                size: 14,
                text: 'Real U.S. prices\nand income, 1995 = 100%',
                align: 'mc',
                color: '#222',
                width: 15,
                italic: false,
                underline: false,
                showMobile: true,
                showDesktop: true,
                mobileFallback: true,
                connectorLine: {
                    type: 'straight',
                    circle: false,
                    stroke: 1,
                    enabled: false,
                    arrowHead: 'lines',
                    circleStyle: 'solid',
                    circleRadius: 15,
                    targetPadding: 4,
                    inheritColor: false
                }
            },
            {
                x: 660,
                y: 220,
                bg: false,
                dx: 0,
                dy: 0,
                bold: false,
                size: 14,
                text: 'Change in\nhousehold\nincome,\n1979 to\n2018',
                align: 'ml',
                color: '#222',
                width: 15,
                italic: false,
                underline: false,
                showMobile: true,
                showDesktop: true,
                mobileFallback: true,
                connectorLine: {
                    type: 'straight',
                    circle: false,
                    stroke: 1,
                    enabled: false,
                    arrowHead: 'lines',
                    circleStyle: 'solid',
                    circleRadius: 15,
                    targetPadding: 4,
                    inheritColor: false
                }
            },
            {
                x: 190,
                y: 320,
                bg: false,
                dx: 0,
                dy: 100,
                bold: false,
                size: 14,
                text: 'Annual hours\nworked by women',
                align: 'mc',
                color: '#222',
                width: 25,
                italic: false,
                underline: false,
                showMobile: true,
                showDesktop: true,
                mobileFallback: true,
                connectorLine: {
                    type: 'straight',
                    circle: false,
                    stroke: 1,
                    enabled: true,
                    arrowHead: 'lines',
                    circleStyle: 'solid',
                    circleRadius: 15,
                    targetPadding: 4,
                    inheritColor: false
                }
            },
            {
                x: 400,
                y: 460,
                bg: false,
                dx: 50,
                dy: 0,
                bold: false,
                size: 14,
                text: 'Lowest 20 percent',
                align: 'mr',
                color: '#222',
                width: 20,
                italic: false,
                underline: false,
                showMobile: true,
                showDesktop: true,
                mobileFallback: true,
                connectorLine: {
                    type: 'straight',
                    circle: false,
                    stroke: 1,
                    enabled: true,
                    arrowHead: 'lines',
                    circleStyle: 'solid',
                    circleRadius: 15,
                    targetPadding: 4,
                    inheritColor: false
                }
            }
        ],
        'range-annotations': [
            {
                display: 'range',
                type: 'x',
                x0: 200,
                x1: 360,
                y0: 0,
                y1: 600,
                color: '#888',
                opacity: 10,
                strokeWidth: 1,
                strokeType: 'solid'
            },
            {
                display: 'range',
                type: 'x',
                x0: 680,
                x1: 720,
                y0: 0,
                y1: 600,
                color: '#888',
                opacity: 40,
                strokeWidth: 1,
                strokeType: 'solid'
            },
            {
                display: 'range',
                type: 'y',
                x0: 0,
                x1: 800,
                y0: 140,
                y1: 270,
                color: '#888',
                opacity: 10,
                strokeWidth: 1,
                strokeType: 'solid'
            },
            {
                display: 'line',
                type: 'y',
                x0: 0,
                x1: 800,
                y0: 290,
                y1: 290,
                color: '#888',
                opacity: 50,
                strokeWidth: 1,
                strokeType: 'solid'
            }
        ]
    }
};
